### ISSUE TITLE
unhandled exception if input is empty

### ISSUE THREAD

**Issue by we-lu** [dxstiny/cs-scalerCalc#1]
When I have no input and press calculate, the following error message appears:

![image](https://user-images.githubusercontent.com/48621230/112727907-02e42480-8f25-11eb-9603-15b5162b6299.png)

**Comment by davidohnee** [comment]
Thank you for your feedback.
We have added this issue to the known issues page and will fix it in the next update.
By the way, our calculator is more effective when you enter data (target period and timer), so you should still be able to use it in the meantime.

**Comment by davidohnee** [comment]
@Claythve your issue has been resolved in ScalerCalc 1.4
